spring:
  application:
    name: weather-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:weather}?createDatabaseIfNotExist=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/master.xml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: ${LOGGING_LEVEL_WEB:debug}

ip-api:
  base-url: http://ip-api.com
  url-json: ${ip-api.base-url}/json/{ip}
open-meteo:
  base-url: https://api.open-meteo.com/v1/forecast
  current-weather-url: ${open-meteo.base-url}/?latitude={latitude}&longitude={longitude}&current_weather=true&temperature_unit={unit}

